ai_service_platform/core/models.py
from typing import Optional, Any
from typing_extensions import Annotated
import uuid
from sqlalchemy.orm.properties import MappedColumn

from . import db
from sqlalchemy import PickleType, event, ForeignKey
from sqlalchemy.orm import mapped_column, Mapped, relationship, DeclarativeBase
from sqlalchemy.dialects.sqlite import JSON
from flask import current_app
from werkzeug.security import generate_password_hash
import enum


class Role(enum.Enum):
    """Role of a user in the system"""

    ADMIN = "admin"
    DEV = "dev"
    USER1 = "user1"
    USER2 = "user2"
    SOURCE = "source"


class RequestStatus(enum.Enum):
    """The  status of a request"""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    FAILED = "failed"
    FINISHED = "finished"


bytes_pickle = Annotated[Any, "pickle"]


class Base(DeclarativeBase):
    type_annotation_map = {
        dict[str, Any]: JSON,
        bytes_pickle: PickleType,
    }


class User(Base):
    __tablename__ = "user"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(unique=True)
    password: Mapped[str]
    role: Mapped[Role]
    requests: Mapped[list["Request"]] = relationship(
        back_populates="user", cascade="all, delete"
    )
    sources: Mapped[list["Source"]] = relationship(
        back_populates="owner", cascade="all, delete"
    )


@event.listens_for(User.__table__, "after_create")
def create_users(*args, **kwargs):
    if current_app.config["TESTING"]:
        return
    db.session.add(
        User(
            public_id=uuid.uuid4(),
            name="admin",
            password=generate_password_hash("admin"),
            role=Role.ADMIN,
        )
    )
    db.session.add(
        User(
            public_id=uuid.uuid4(),
            name="user1",
            password=generate_password_hash("user1"),
            role=Role.USER1,
        )
    )
    db.session.commit()


class Request(Base):
    __tablename__ = "request"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("user.public_id", ondelete="CASCADE")
    )
    source_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("source.public_id", ondelete="CASCADE")
    )
    model_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("model.public_id", ondelete="CASCADE")
    )
    patient_id: Mapped[Optional[str]]
    input_file: Mapped[str]
    output: Mapped[Optional[bytes_pickle]]
    status: Mapped[RequestStatus] = mapped_column(default=RequestStatus.PENDING)
    user: Mapped[User] = relationship(back_populates="requests")
    source: Mapped["Source"] = relationship(back_populates="requests")
    model: Mapped["Model"] = relationship(back_populates="requests")


class Model(Base):
    __tablename__ = "model"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(unique=True)
    binary: Mapped[Optional[bytes]]
    config: Mapped[dict[str, Any]]
    type: Mapped[str]
    requests: Mapped[list[Request]] = relationship(
        back_populates="model", cascade="all, delete"
    )


@event.listens_for(Model.__table__, "after_create")
def create_models(*args, **kwargs):
    if current_app.config["TESTING"]:
        return
    db.session.add(
        Model(
            public_id=uuid.uuid4(),
            name="MobileNet",
            config={"shape": (224, 224), "expand_dims": True},
            type="keras",
        )
    )
    db.session.commit()


class Source(Base):
    __tablename__ = "source"
    public_id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    owner_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.public_id"))
    name: Mapped[str]
    password: Mapped[str]
    role: Mapped[Role] = mapped_column(default=Role.SOURCE)
    owner: Mapped[list[User]] = relationship(back_populates="sources")
    requests: Mapped[list[Request]] = relationship(back_populates="source")

ai_service_platform/models/__init__.py
from flask_sqlalchemy_lite import SQLAlchemy

db = SQLAlchemy()

ai_service_platform/models/models.py
from typing import Optional, Any
from typing_extensions import Annotated
import uuid
from sqlalchemy.orm.properties import MappedColumn

from . import db
from sqlalchemy import PickleType, event, ForeignKey
from sqlalchemy.orm import mapped_column, Mapped, relationship, DeclarativeBase
from sqlalchemy.dialects.sqlite import JSON
from flask import current_app
from werkzeug.security import generate_password_hash
import enum


class Role(enum.Enum):
    """Role of a user in the system"""

    ADMIN = "admin"
    DEV = "dev"
    USER1 = "user1"
    USER2 = "user2"
    SOURCE = "source"


class RequestStatus(enum.Enum):
    """The  status of a request"""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    FAILED = "failed"
    FINISHED = "finished"


bytes_pickle = Annotated[Any, "pickle"]


class Base(DeclarativeBase):
    type_annotation_map = {
        dict[str, Any]: JSON,
        bytes_pickle: PickleType,
    }


class User(Base):
    __tablename__ = "user"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(unique=True)
    password: Mapped[str]
    role: Mapped[Role]
    requests: Mapped[list["Request"]] = relationship(
        back_populates="user", cascade="all, delete"
    )
    sources: Mapped[list["Source"]] = relationship(
        back_populates="owner", cascade="all, delete"
    )


@event.listens_for(User.__table__, "after_create")
def create_users(*args, **kwargs):
    if current_app.config["TESTING"]:
        return
    db.session.add(
        User(
            public_id=uuid.uuid4(),
            name="admin",
            password=generate_password_hash("admin"),
            role=Role.ADMIN,
        )
    )
    db.session.add(
        User(
            public_id=uuid.uuid4(),
            name="user1",
            password=generate_password_hash("user1"),
            role=Role.USER1,
        )
    )
    db.session.commit()


class Request(Base):
    __tablename__ = "request"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("user.public_id", ondelete="CASCADE")
    )
    source_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        ForeignKey("source.public_id", ondelete="CASCADE")
    )
    model_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("model.public_id", ondelete="CASCADE")
    )
    patient_id: Mapped[Optional[str]]
    # input_name: Mapped[str]
    input_file: Mapped[str]
    output: Mapped[Optional[bytes_pickle]]
    status: Mapped[RequestStatus] = mapped_column(default=RequestStatus.PENDING)
    user: Mapped[User] = relationship(back_populates="requests")
    source: Mapped["Source"] = relationship(back_populates="requests")
    model: Mapped["Model"] = relationship(back_populates="requests")


class Model(Base):
    __tablename__ = "model"
    public_id: MappedColumn[uuid.UUID] = mapped_column(
        primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(unique=True)
    server_model_name: Mapped[str] = mapped_column(unique=True)
    requests: Mapped[list[Request]] = relationship(
        back_populates="model", cascade="all, delete"
    )


@event.listens_for(Model.__table__, "after_create")
def create_models(*args, **kwargs):
    if current_app.config["TESTING"]:
        return
    db.session.add(
        Model(
            public_id=uuid.uuid4(),
            name="SqueezeNet",
            server_model_name="squeezenet",
        ))

    db.session.add(
        Model(
            public_id=uuid.uuid4(),
            name="FERPlus",
            server_model_name="FERPlus",
        ))

    db.session.commit()


class Source(Base):
    __tablename__ = "source"
    public_id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    owner_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("user.public_id"))
    name: Mapped[str]
    password: Mapped[str]
    role: Mapped[Role] = mapped_column(default=Role.SOURCE)
    owner: Mapped[list[User]] = relationship(back_populates="sources")
    requests: Mapped[list[Request]] = relationship(back_populates="source")

ai_service_platform/models/request_handler.py
from flask import current_app
import os
import requests

from . import db
from .models import Request, RequestStatus


def process_request(request_id: str) -> None:
    """Handles the predictions of an ai request. The request is loaded from the database an then the model is run

    Args:
        request_id: The public_id of the request to process

    Returns:
        A list of predictions
    """
    request = db.session.get(Request, request_id)
    if not request:
        return

    request.status = RequestStatus.RUNNING
    db.session.commit()

    input_path = os.path.join(current_app.config["UPLOAD_FOLDER"], request.input_file)
    prediction_url = f"http://multi-model-server:8080/predictions/{request.model.server_model_name}"

    with open(input_path, "rb") as file:
        response = requests.post(prediction_url, data=file).json()

    request.status = RequestStatus.FINISHED
    request.output = response
    db.session.commit()

ai_service_platform/apis/auth.py
from flask import (
    request,
    g,
    render_template,
    session,
    redirect,
    url_for,
    flash,
    Blueprint,
)

from sqlalchemy import select
from werkzeug.security import check_password_hash
from functools import wraps

from ai_service_platform.core.models import User, Role
from ai_service_platform.core import db

bp = Blueprint("auth", __name__, url_prefix="/auth")


def roles_required(allowed: list[Role]):
    """Checks if current user has at least one of the allowed roles

    This decorator used the g object to read the current user.

    Args:
    allowed: A list of allowed roles. Can be any combination of user1, user2, admin, dev, source
    """

    def decorator(f):
        @wraps(f)
        def decorated(*args, **kwargs):
            if g.user is None:
                flash("Not logged in")
                return redirect(url_for("auth.login", next_page=request.url))
            if g.user.role not in allowed:
                flash("Access denied")
                return redirect(request.referrer)

            return f(*args, **kwargs)

        return decorated

    return decorator


@bp.before_app_request
def load_logged_in_user():
    """Load user from the current session cookie"""
    g.user = None
    user_id: str | None = session.get("user_id")

    if user_id:
        try:
            g.user = db.session.get_one(User, user_id)
        except Exception:
            pass


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        user = db.session.scalar(select(User).filter_by(name=username))

        if not user or not check_password_hash(user.password, password):
            flash("Incorrect username or password")
            return redirect(request.url)

        session.clear()
        session["user_id"] = user.public_id

        next_page = request.args.get("next_page")
        if next_page:
            return redirect(next_page)

        return redirect(url_for("index"))

    return render_template("auth/login.html")


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))

ai_service_platform/views/model.py
from flask import render_template, Blueprint
from sqlalchemy import select

from .auth import roles_required
from ai_service_platform.models.models import Role, Model
from ai_service_platform.models import db

bp = Blueprint("model", __name__, url_prefix="/model")


@bp.route("")
@roles_required([Role.USER1, Role.SOURCE])
def model():
    models = db.session.scalars(select(Model))

    return render_template("models.html", models=models)

ai_service_platform/views/user.py
import uuid

from sqlalchemy import select
from werkzeug.security import generate_password_hash

from flask import (
    Blueprint,
    render_template,
    request,
    flash,
)

from ai_service_platform.models import db
from ai_service_platform.models import models
from ai_service_platform.models.models import Role, User
from .auth import roles_required


bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("", methods=["GET", "POST"])
@roles_required([Role.ADMIN])
def user():
    if request.method == "POST":
        data = {
            "name": request.form["username"],
            "password": generate_password_hash(request.form["password"]),
            "role": request.form["role"],
        }

        user = models.User(**data)

        try:
            db.session.add(user)
            db.session.commit()
        except Exception:
            db.session.close()
            flash("Error creating user")

    users = db.session.scalars(select(User))
    return render_template(
        "users.html",
        users=users,
        roles=[Role.ADMIN, Role.USER1, Role.USER2, Role.DEV],
    )


@bp.route("/<uuid:public_id>", methods=["DELETE"])
@roles_required([Role.ADMIN])
def delete(public_id):
    user = db.session.get(models.User, public_id)

    if not user:
        return "", 404

    db.session.delete(user)
    db.session.commit()

    return ""

ai_service_platform/templates/base.html
<!doctype html>
<html lang="en" class="text-gray-900 antialiased">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} - AI-Service-Platform</title>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.indigo.min.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}" />
</head>

<body class="container">
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{{ url_for('index') }}"><strong>AI-Service-Platform</strong></a>
                </li>
            </ul>
            <ul>
                {% if g.user %}
                <li>
                    <a class="outline" role="button" href="{{ url_for('auth.logout') }}">
                        Logout
                    </a>
                </li>

                {% else %}
                <li>
                    <a role="button" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        <header>{% block header %}{% endblock %}</header>
        {% for message in get_flashed_messages() %}
        <article class="warning">{{ message }}</article>
        {% endfor %}
        {% block content %}{% endblock %}
    </main>
    <footer></footer>
</body>

</html>

ai_service_platform/templates/index.html
{% extends 'base.html' %} {% block header %} {% endblock %} {% block content %}
<nav>
    <ul>
        <li>
            <a aria-current="{{ 'page' if request.path == url_for('index') else ''}}"
                href="{{ url_for('index') }}">Home</a>
        </li>
        {% if g.user.role.name == "ADMIN" %}
        <li><a href="{{ url_for('user.user') }}">Admin Area</a></li>
        {% endif%} {% if g.user.role.name == "USER1" %}
        <li>
            <a aria-current="{{ 'page' if request.path == url_for('request.get') else ''}}"
                href="{{ url_for('request.get') }}">Requests</a>
        </li>
        <li>
            <a aria-current="{{ 'page' if request.path == url_for('model.model') else ''}}"
                href="{{ url_for('model.model') }}">Models</a>
        </li>
    </ul>
</nav>
{% endif %}
<!-- <div id="main-layout-container" class="grid">
    <aside>
        <nav>
            <ul>
                <li>
                    <a href="{{ url_for('index') }}">Home</a>
                </li>
                {% if g.user.role.name == "ADMIN" %}
                <li><a href="{{ url_for('user.user') }}">Admin Area</a></li>
                {% endif%} {% if g.user.role.name == "USER1" %}
                <li>
                    <a href="{{ url_for('request.get') }}">Requests</a>
                </li>
                <li>
                    <a href="{{ url_for('model.model') }}">Models</a>
                </li>
                {% endif%}
            </ul>
        </nav>
    </aside>
    <section>

    </section>
</div> -->
{% endblock %}

ai_service_platform/templates/models.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %}Available AI Models{% endblock %}</h1>
{% endblock %} {% block content %} {% for model in models %}
<article>
    <header>{{model.name}}</header>
    <main>...</main>
</article>
{% endfor %} {% endblock %}

ai_service_platform/templates/users.html
{% extends 'base.html' %} {% block header %}
<h1>{% block title %}List of Users{% endblock %}</h1>
{% endblock %} {% block content %}
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Role</th>
            <th></th>
        </tr>
    </thead>
    {% for user in users %}
    <tr>
        <td>{{user.name}}</td>
        <td>{{user.role.name}}</td>
        <td>
            <button
                hx-delete="{{ url_for('user.delete', public_id=user.public_id) }}"
                hx-confirm="Really delete this account?"
                hx-target="closest tr"
            >
                <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
        </td>
    </tr>
    {% endfor %}
</table>
<h2>Create User</h2>
<form method="post">
    <label for="username">Username</label>
    <input name="username" required />
    <label for="pasword">Password</label>
    <input name="password" type="password" required />
    <select name="role" required>
        {%for role in roles%}
        <option value="{{role.name}}">{{role.name}}</option>
        {%endfor %}
    </select>
    <input type="submit" value="Create User" />
</form>

{% endblock %}